"""Finance Upload Errors

Revision ID: 9f86d663257a
Revises: 1614b11e62de
Create Date: 2025-05-15 14:29:32.303657

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f86d663257a'
down_revision = '1614b11e62de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_upload_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finance_upload_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('row', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('last_update_date', sa.DateTime(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_update_by', sa.String(length=200), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['finance_upload_id'], ['finance_upload.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_upload_message_finance_upload_id'), 'finance_upload_message', ['finance_upload_id'], unique=False)
    op.create_index(op.f('ix_finance_upload_message_type'), 'finance_upload_message', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finance_upload_message_type'), table_name='finance_upload_message')
    op.drop_index(op.f('ix_finance_upload_message_finance_upload_id'), table_name='finance_upload_message')
    op.drop_table('finance_upload_message')
    # ### end Alembic commands ###
