"""Create External Funding

Revision ID: a26b79b851b6
Revises: 9f86d663257a
Create Date: 2025-05-21 15:56:38.881790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a26b79b851b6'
down_revision = '9f86d663257a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_funding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('research_council', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('research_charity', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('dhsc_nihr', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('industry_collaborative', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('industry_contract', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('other_non_commercial', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('last_update_date', sa.DateTime(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_update_by', sa.String(length=200), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('external_funding')
    # ### end Alembic commands ###
